CREATE TABLE `olympicsc`.`CUSTOMVALUE` (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `TYPE` VARCHAR(45) NOT NULL,
  `ID_CUSTOMVALUETYPE` INTEGER UNSIGNED NOT NULL,
  `ID_EVENT` INTEGER UNSIGNED,
  `ID_USER` INTEGER UNSIGNED,
  `ID_ACTIVITY` INTEGER UNSIGNED,
  `VALUE` VARCHAR(255),
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB;
